/**
 * FRAGMENTS — archive manifest.
 *
 * The archive is data-driven: adding, replacing or removing an asset is a
 * manifest edit, never a component change. Every entry carries its identity
 * label and context line; nothing is displayed beyond what the archive
 * documents (see FRAGMENTS_FACTUAL_VERIFICATION_v1.md — names only where the
 * filename evidence supports them, no invented dates or venues).
 */

export type FragmentsBand = "people" | "places" | "moments" | "evidence";

export type FragmentsItem = {
  id: string;
  media: string;
  band: FragmentsBand;
  /** Identity label — the person / place / event name line (museum plate). */
  name: string;
  /** Muted context line — only what the archive filename documents. */
  context?: string;
  alt: string;
  /** Rhythm classes: column span (desktop) + aspect fitted to the source frame. */
  span?: string;
  aspect: string;
};

export type FieldFragment = {
  id: string;
  /** base position (% of the scene) — the archive's resting place */
  pos: { left: number; top: number };
  /** width in vw — fragments are small (8–15% of viewport width) */
  w: number;
  /** resting rotation (deg) */
  rot: number;
  /** cycle length in seconds — every fragment has its own speed */
  period: number;
  /** phase 0–1 — every fragment has its own rhythm */
  phase: number;
  /** lateral drift amplitude (vw) */
  ampX: number;
  /** vertical drift amplitude (vh) */
  ampY: number;
  /** rotation oscillation (deg) */
  rotAmp: number;
  /** scale oscillation — approach and recede */
  scaleAmp: number;
  /** long presence cycle: the fragment fades out, vanishes, and returns */
  presence?: { period: number; phase: number; min: number };
  /** above (z-20) or behind (z-10) the hero photograph */
  above?: boolean;
  /**
   * Depth layer — the archival table stacks in tiers: primary = the curated
   * selection (dominant, flips above/below the hero); secondary = mid archive
   * (smaller, never flips, always below primaries AND the hero); deep = the
   * dense underlayer (smallest, partially obscured, never flips).
   */
  layer?: "primary" | "secondary" | "deep";
  /** Suppress the printed caption — deep/secondary prints are too small to
   *  read; captions only exist on legible primary pieces. */
  label?: boolean;
  /** Self-contained media for archive layers that have no items[] gallery
   *  entry (the render falls back to this instead of byId). */
  media?: string;
  alt?: string;
  /** include on mobile (explicit — mobile shows fewer fragments) */
  mobile?: boolean;
  /** exclude on tablet (default: included) */
  tablet?: boolean;
  /**
   * Physical evidence object (transplanted from the original Living Archive
   * build): instant = Polaroid mount, flyer = clipped print (no caption —
   * flyers carry their own typography), pass = credential card with punch
   * hole, jcard = CD card with photo floating beside its caption.
   */
  variant: "instant" | "flyer" | "pass" | "jcard";
  /** evidence weight — primary = larger, background = recedes */
  tier: "primary" | "supporting" | "background";
  /** masking tape on the mount edge */
  tape?: boolean;
  tapeRot?: number;
};

export const fragments = {
  hero: {
    media: "/assets/fragments/fragments-hero.jpg",
    alt: "DJ Lethal Skillz with Grandmaster Flash, archival photograph",
    // The safe public-facing identification. No date, no venue — the archive
    // has none for this photograph (FRAGMENTS_FACTUAL_VERIFICATION_v1.md).
    name: "WITH GRANDMASTER FLASH",
  },
  statement: {
    headline: "A LIFE INSIDE THE CULTURE.",
    body: [
      "Photographs, places and documents from a career lived inside hip-hop: the people who built it, the rooms where it happened, the work that came out of it.",
      "Names are part of the archive. Every important figure in these frames is identified.",
    ],
  },
  /**
   * FIELD — ONE LIVING CINEMATIC SCENE. Skillz + Grandmaster Flash are the
   * gravitational centre; the archive moves around them. The field is
   * TIME-driven (not scroll-driven): each fragment carries its own period,
   * phase, drift amplitudes, rotation and scale oscillation, and — for some —
   * a long presence cycle (fade out, vanish, return). Periods are deliberately
   * non-common-multiple so the field never repeats. At rest (and under
   * prefers-reduced-motion) the same positions form the static composition.
   */
  field: [
    // ── PEOPLE — the strongest prints, spread across the field's anchor
    // zones (corners + edges); the hero keeps the centre ──────────────
    {
      id: "qbert",
      pos: { left: 47.1, top: 94 },
      w: 9,
      rot: -3,
      period: 50,
      phase: 0.0,
      ampX: 6,
      ampY: 7,
      rotAmp: 4,
      scaleAmp: 0.1,
      above: true,
      mobile: true,
      variant: "instant",
      tier: "primary",
      tape: true,
      tapeRot: -6,
    },
    {
      id: "tony-touch-apollo-vinroc",
      pos: { left: 97, top: 45.7 },
      w: 10,
      rot: 2,
      period: 66,
      phase: 0.22,
      ampX: 5,
      ampY: 6,
      rotAmp: -5,
      scaleAmp: 0.08,
      above: true,
      mobile: true,
      variant: "instant",
      tier: "primary",
    },
    {
      id: "keith-shocklee",
      pos: { left: 80.6, top: 10.3 },
      w: 8.5,
      rot: 2,
      period: 75,
      phase: 0.31,
      ampX: 7,
      ampY: 5,
      rotAmp: -3,
      scaleAmp: 0.06,
      above: true,
      mobile: true,
      variant: "instant",
      tier: "primary",
    },
    {
      id: "jazzy-jeff",
      pos: { left: 3, top: 61.6 },
      w: 7.5,
      rot: -2,
      period: 42,
      phase: 0.47,
      ampX: 5,
      ampY: 8,
      rotAmp: 5,
      scaleAmp: 0.09,
      above: true,
      mobile: true,
      variant: "instant",
      tier: "supporting",
    },
    {
      id: "rob-swift",
      pos: { left: 81.2, top: 29.7 },
      w: 6.5,
      rot: 3,
      period: 53,
      phase: 0.13,
      ampX: 4,
      ampY: 6,
      rotAmp: -4,
      scaleAmp: 0.07,
      presence: { period: 48, phase: 0.2, min: 0.15 }, // the ghost that emerges
      above: true,
      variant: "instant",
      tier: "supporting",
    },
    {
      id: "sueside",
      pos: { left: 13.9, top: 46.1 },
      w: 8.5,
      rot: -2,
      period: 83,
      phase: 0.61,
      ampX: 6,
      ampY: 4,
      rotAmp: 4,
      scaleAmp: 0.08,
      above: true,
      variant: "instant",
      tier: "supporting",
    },
    {
      id: "nu-mark",
      pos: { left: 85.5, top: 71.8 },
      w: 6.5,
      rot: 2,
      period: 59,
      phase: 0.75,
      ampX: 8,
      ampY: 5,
      rotAmp: -5,
      scaleAmp: 0.09,
      above: true,
      variant: "instant",
      tier: "supporting",
    },
    {
      id: "cut-killer",
      pos: { left: 97, top: 4.62 },
      w: 9,
      rot: -1,
      period: 46,
      phase: 0.88,
      ampX: 9,
      ampY: 6,
      rotAmp: 3,
      scaleAmp: 0.07,
      above: true,
      variant: "instant",
      tier: "supporting",
    },
    // ── FLYERS + DOCUMENTS — clipped prints, own typography, no captions ─
    {
      id: "one-nation",
      pos: { left: 9.24, top: 6.33 },
      w: 10,
      rot: -4,
      period: 69,
      phase: 0.05,
      ampX: 7,
      ampY: 5,
      rotAmp: 7,
      scaleAmp: 0.11,
      above: false, // crosses BEHIND the hero
      mobile: true,
      variant: "flyer",
      tier: "primary",
      tape: true,
      tapeRot: 5,
    },
    {
      id: "3style",
      pos: { left: 3, top: 42 },
      w: 7.5,
      rot: 1,
      period: 56,
      phase: 0.68,
      ampX: 7,
      ampY: 9,
      rotAmp: -3,
      scaleAmp: 0.07,
      above: false, // drifts behind the hero
      tablet: false,
      variant: "flyer",
      tier: "supporting",
    },
    {
      id: "breaking",
      pos: { left: 14, top: 94 },
      w: 6.5,
      rot: 2,
      period: 43,
      phase: 0.34,
      ampX: 6,
      ampY: 4,
      rotAmp: -4,
      scaleAmp: 0.1,
      presence: { period: 42, phase: 0.6, min: 0.3 },
      above: true,
      tablet: false,
      variant: "flyer",
      tier: "supporting",
    },
    {
      id: "cambodia",
      pos: { left: 97, top: 35.9 },
      w: 6,
      rot: 3,
      period: 70,
      phase: 0.82,
      ampX: 5,
      ampY: 6,
      rotAmp: 3,
      scaleAmp: 0.08,
      presence: { period: 61, phase: 0.15, min: 0.25 },
      above: true,
      tablet: false,
      variant: "flyer",
      tier: "supporting",
    },
    // ── PLACES + MOMENTS + EVIDENCE ─────────────────────────────────────
    {
      id: "beirut-streets",
      pos: { left: 55, top: 6.61 },
      w: 10,
      rot: 1,
      period: 61,
      phase: 0.56,
      ampX: 8,
      ampY: 4,
      rotAmp: -2,
      scaleAmp: 0.06,
      above: true,
      mobile: true,
      variant: "instant",
      tier: "primary",
    },
    {
      id: "stussy",
      pos: { left: 82.2, top: 57.6 },
      w: 7.5,
      rot: 1,
      period: 93,
      phase: 0.4,
      ampX: 6,
      ampY: 6,
      rotAmp: -5,
      scaleAmp: 0.1,
      presence: { period: 80, phase: 0.4, min: 0.35 },
      above: true,
      tablet: false,
      variant: "instant",
      tier: "supporting",
    },
    {
      id: "ufo-badge",
      pos: { left: 31.1, top: 3 },
      w: 6,
      rot: -2,
      period: 37,
      phase: 0.9,
      ampX: 5,
      ampY: 7,
      rotAmp: 4,
      scaleAmp: 0.09,
      presence: { period: 70, phase: 0.55, min: 0 }, // surfaces late, recedes
      above: true,
      mobile: true,
      variant: "pass",
      tier: "background",
      tape: true,
      tapeRot: -8,
    },
    {
      id: "studio-2012",
      pos: { left: 25, top: 85.5 },
      w: 6.5,
      rot: -1,
      period: 78,
      phase: 0.1,
      ampX: 4,
      ampY: 5,
      rotAmp: 2,
      scaleAmp: 0.06,
      above: false, // below the field, behind the hero
      tablet: false,
      variant: "jcard",
      tier: "background",
    },
    // ── SECONDARY ARCHIVE — mid tier, below the curated selection. The
    // gallery-only people prints, clustered (right stack, bottom-left pile,
    // top-left scatter) — never evenly spaced, never above a primary. ────
    {
      id: "s-akakabe-dmc",
      pos: { left: 97, top: 28 },
      w: 6,
      rot: 2,
      period: 47,
      phase: 0.08,
      ampX: 5,
      ampY: 6,
      rotAmp: -4,
      scaleAmp: 0.07,
      mobile: true,
      layer: "secondary",
      label: false,
      media: "/assets/fragments/fragments-akakabe-dmc.jpg",
      alt: "Skillz with DJ Akakabe — archive print",
      variant: "instant",
      tier: "background",
      tape: true,
      tapeRot: 7,
    },
    {
      id: "s-japan-champions",
      pos: { left: 10.9, top: 33.2 },
      w: 5.5,
      rot: -3,
      period: 63,
      phase: 0.21,
      ampX: 4,
      ampY: 5,
      rotAmp: 5,
      scaleAmp: 0.08,
      layer: "secondary",
      label: false,
      media: "/assets/fragments/fragments-japan-champions.jpg",
      alt: "Japan's DMC Champions with Skillz — archive print",
      variant: "instant",
      tier: "background",
      tape: true,
      tapeRot: -4,
    },
    {
      id: "s-coma-sarasa",
      pos: { left: 5.61, top: 94 },
      w: 5,
      rot: 1,
      period: 51,
      phase: 0.44,
      ampX: 6,
      ampY: 7,
      rotAmp: -3,
      scaleAmp: 0.06,
      layer: "secondary",
      label: false,
      media: "/assets/fragments/fragments-coma-sarasa.jpg",
      alt: "Skillz with Coma and Sarasa — archive print",
      variant: "instant",
      tier: "background",
    },
    {
      id: "s-tony-touch",
      pos: { left: 24.9, top: 94 },
      w: 5.5,
      rot: -2,
      period: 58,
      phase: 0.63,
      ampX: 5,
      ampY: 4,
      rotAmp: 4,
      scaleAmp: 0.07,
      presence: { period: 63, phase: 0.12, min: 0.25 },
      layer: "secondary",
      label: false,
      media: "/assets/fragments/fragments-tony-touch.jpg",
      alt: "Skillz with DJ Tony Touch — archive print",
      variant: "instant",
      tier: "background",
    },
    {
      id: "s-sarasa",
      pos: { left: 67.7, top: 3 },
      w: 5,
      rot: 3,
      period: 44,
      phase: 0.72,
      ampX: 5,
      ampY: 5,
      rotAmp: -5,
      scaleAmp: 0.09,
      mobile: true,
      layer: "secondary",
      label: false,
      media: "/assets/fragments/fragments-sarasa.jpg",
      alt: "Skillz with DJ Sarasa — archive print",
      variant: "instant",
      tier: "background",
    },
    {
      id: "s-mims",
      pos: { left: 37.8, top: 93.4 },
      w: 5.5,
      rot: -1,
      period: 55,
      phase: 0.29,
      ampX: 6,
      ampY: 6,
      rotAmp: 3,
      scaleAmp: 0.07,
      mobile: true,
      layer: "secondary",
      label: false,
      media: "/assets/fragments/fragments-mims.jpg",
      alt: "Skillz with MIMS — clipped print",
      variant: "flyer",
      tier: "background",
    },
    {
      id: "s-primecuts",
      pos: { left: 80.2, top: 44.7 },
      w: 5,
      rot: 2,
      period: 49,
      phase: 0.87,
      ampX: 5,
      ampY: 5,
      rotAmp: -4,
      scaleAmp: 0.06,
      layer: "secondary",
      label: false,
      media: "/assets/fragments/fragments-primecuts.jpg",
      alt: "Skillz with DJ Primecuts — archive print",
      variant: "instant",
      tier: "background",
    },
    {
      id: "s-naughty-j",
      pos: { left: 19.7, top: 56.4 },
      w: 6,
      rot: -2,
      period: 67,
      phase: 0.35,
      ampX: 6,
      ampY: 6,
      rotAmp: 2,
      scaleAmp: 0.08,
      layer: "secondary",
      label: false,
      media: "/assets/fragments/fragments-naughty-j.jpg",
      alt: "Skillz with DJ Naughty J — jcard",
      variant: "jcard",
      tier: "background",
      tape: true,
      tapeRot: 6,
    },
    {
      id: "s-big-ali-mice",
      pos: { left: 29.8, top: 12 },
      w: 5,
      rot: 1,
      period: 73,
      phase: 0.51,
      ampX: 4,
      ampY: 7,
      rotAmp: -3,
      scaleAmp: 0.07,
      layer: "secondary",
      label: false,
      media: "/assets/fragments/fragments-big-ali-mice.jpg",
      alt: "Skillz with Big Ali and M.ICE — clipped print",
      variant: "flyer",
      tier: "background",
    },
    // ── DEEP ARCHIVE — the dense underlayer. Same prints at small scale,
    // stacked in organic piles at the table edges, half-obscured by the
    // layers above. Duplicate prints are deliberate (archives hold several). ─
    {
      id: "d-qbert",
      pos: { left: 72.3, top: 94 },
      w: 4,
      rot: -4,
      period: 59,
      phase: 0.05,
      ampX: 4,
      ampY: 5,
      rotAmp: 6,
      scaleAmp: 0.08,
      presence: { period: 71, phase: 0.2, min: 0.35 },
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-qbert.jpg",
      alt: "Skillz with DJ Q-Bert — deep archive print",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-cambodia",
      pos: { left: 62.6, top: 3 },
      w: 3.5,
      rot: 2,
      period: 41,
      phase: 0.61,
      ampX: 5,
      ampY: 4,
      rotAmp: -4,
      scaleAmp: 0.07,
      tablet: false,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-cambodia.jpg",
      alt: "Cambodia performance — deep archive print",
      variant: "flyer",
      tier: "background",
    },
    {
      id: "d-3style",
      pos: { left: 97, top: 84.5 },
      w: 4,
      rot: 1,
      period: 79,
      phase: 0.33,
      ampX: 4,
      ampY: 6,
      rotAmp: 3,
      scaleAmp: 0.09,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-3style.jpg",
      alt: "Red Bull 3Style — deep archive print",
      variant: "flyer",
      tier: "background",
    },
    {
      id: "d-nu-mark",
      pos: { left: 17.5, top: 3 },
      w: 4,
      rot: -2,
      period: 52,
      phase: 0.77,
      ampX: 6,
      ampY: 5,
      rotAmp: -5,
      scaleAmp: 0.06,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-nu-mark.jpg",
      alt: "Skillz with DJ Nu-Mark — deep archive print",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-ufo",
      pos: { left: 56.4, top: 94 },
      w: 3.5,
      rot: 3,
      period: 64,
      phase: 0.12,
      ampX: 4,
      ampY: 4,
      rotAmp: 4,
      scaleAmp: 0.08,
      presence: { period: 68, phase: 0.55, min: 0.2 },
      mobile: true,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-ufo-badge.png",
      alt: "UFO Radio badge — deep archive",
      variant: "pass",
      tier: "background",
    },
    {
      id: "d-jazzy",
      pos: { left: 89, top: 3 },
      w: 4,
      rot: 2,
      period: 46,
      phase: 0.41,
      ampX: 4,
      ampY: 5,
      rotAmp: -3,
      scaleAmp: 0.07,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-jazzy-jeff.jpg",
      alt: "Skillz with DJ Jazzy Jeff — deep archive print",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-rob-swift",
      pos: { left: 3, top: 29.9 },
      w: 3.5,
      rot: -3,
      period: 57,
      phase: 0.9,
      ampX: 5,
      ampY: 4,
      rotAmp: 5,
      scaleAmp: 0.08,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-rob-swift.jpg",
      alt: "Skillz with Rob Swift — deep archive print",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-studio",
      pos: { left: 46.6, top: 83.8 },
      w: 4.5,
      rot: 1,
      period: 71,
      phase: 0.24,
      ampX: 4,
      ampY: 5,
      rotAmp: -2,
      scaleAmp: 0.06,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-studio-2012.jpg",
      alt: "Studio session — deep archive jcard",
      variant: "jcard",
      tier: "background",
    },
    {
      id: "d-cut-killer",
      pos: { left: 61.9, top: 94 },
      w: 4,
      rot: 3,
      period: 38,
      phase: 0.66,
      ampX: 4,
      ampY: 6,
      rotAmp: 3,
      scaleAmp: 0.09,
      tablet: false,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-cut-killer.jpg",
      alt: "Skillz with DJ Cut Killer — deep archive print",
      variant: "flyer",
      tier: "background",
    },
    {
      id: "d-beirut",
      pos: { left: 81.6, top: 84.7 },
      w: 4.5,
      rot: -2,
      period: 62,
      phase: 0.18,
      ampX: 5,
      ampY: 5,
      rotAmp: 2,
      scaleAmp: 0.07,
      presence: { period: 74, phase: 0.3, min: 0.3 },
      mobile: true,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-beirut-streets.jpg",
      alt: "Beirut street performance — deep archive print",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-stussy",
      pos: { left: 95.1, top: 70.3 },
      w: 4,
      rot: 1,
      period: 83,
      phase: 0.7,
      ampX: 4,
      ampY: 6,
      rotAmp: -4,
      scaleAmp: 0.08,
      tablet: false,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-stussy.jpg",
      alt: "Stussy launch party — deep archive print",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-breaking",
      pos: { left: 97, top: 18.9 },
      w: 4,
      rot: -1,
      period: 45,
      phase: 0.53,
      ampX: 6,
      ampY: 5,
      rotAmp: 3,
      scaleAmp: 0.06,
      mobile: true,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-breaking.jpg",
      alt: "Red Bull breaking battle — deep archive print",
      variant: "flyer",
      tier: "background",
    },
    {
      id: "d-keith",
      pos: { left: 14.6, top: 72.7 },
      w: 3.5,
      rot: 2,
      period: 69,
      phase: 0.08,
      ampX: 5,
      ampY: 4,
      rotAmp: -3,
      scaleAmp: 0.07,
      tablet: false,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-keith-shocklee.jpg",
      alt: "Skillz with Keith Shocklee — deep archive print",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-one-nation",
      pos: { left: 96.4, top: 79.2 },
      w: 4.5,
      rot: 1,
      period: 54,
      phase: 0.29,
      ampX: 5,
      ampY: 5,
      rotAmp: -2,
      scaleAmp: 0.08,
      presence: { period: 66, phase: 0.4, min: 0.35 },
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-one-nation.jpg",
      alt: "One Nation under a groove — deep archive print",
      variant: "flyer",
      tier: "background",
    },
    {
      id: "d-sueside",
      pos: { left: 40.1, top: 14.5 },
      w: 4,
      rot: -3,
      period: 48,
      phase: 0.84,
      ampX: 4,
      ampY: 6,
      rotAmp: 4,
      scaleAmp: 0.07,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-sueside.jpg",
      alt: "Skillz with Grand Master Sueside — deep archive print",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-ufo2",
      pos: { left: 89, top: 29.1 },
      w: 3.5,
      rot: 2,
      period: 76,
      phase: 0.15,
      ampX: 4,
      ampY: 4,
      rotAmp: -5,
      scaleAmp: 0.06,
      tablet: false,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-ufo-badge.png",
      alt: "UFO Radio badge — deep archive",
      variant: "pass",
      tier: "background",
    },
    {
      id: "d-qbert2",
      pos: { left: 45.9, top: 10.9 },
      w: 3.5,
      rot: -1,
      period: 42,
      phase: 0.48,
      ampX: 5,
      ampY: 5,
      rotAmp: 3,
      scaleAmp: 0.08,
      tablet: false,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-qbert.jpg",
      alt: "Skillz with DJ Q-Bert — deep archive print",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-tony-touch",
      pos: { left: 89.8, top: 15.9 },
      w: 4,
      rot: 2,
      period: 61,
      phase: 0.03,
      ampX: 4,
      ampY: 6,
      rotAmp: -3,
      scaleAmp: 0.07,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-tony-touch.jpg",
      alt: "Skillz with DJ Tony Touch — deep archive print",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-japan",
      pos: { left: 97, top: 90.5 },
      w: 4,
      rot: -2,
      period: 87,
      phase: 0.26,
      ampX: 5,
      ampY: 5,
      rotAmp: 4,
      scaleAmp: 0.06,
      tablet: false,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-japan-champions.jpg",
      alt: "Japan DMC Champions — deep archive print",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-cut-killer2",
      pos: { left: 72.5, top: 14.8 },
      w: 4,
      rot: 1,
      period: 56,
      phase: 0.62,
      ampX: 6,
      ampY: 4,
      rotAmp: -2,
      scaleAmp: 0.08,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-cut-killer.jpg",
      alt: "Skillz with DJ Cut Killer — deep archive print",
      variant: "flyer",
      tier: "background",
    },
    {
      id: "d-akakabe",
      pos: { left: 22.7, top: 3 },
      w: 4,
      rot: -3,
      period: 68,
      phase: 0.09,
      ampX: 5,
      ampY: 6,
      rotAmp: 3,
      scaleAmp: 0.07,
      tablet: false,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-akakabe-dmc.jpg",
      alt: "Skillz with DJ Akakabe — deep archive print",
      variant: "instant",
      tier: "background",
    },
    // ── DEEP FILLS — corner + gap texture of the exploded field ────────
    {
      id: "d-flash-beirut",
      pos: { left: 76.5, top: 73.2 },
      w: 3,
      rot: -3,
      period: 47,
      phase: 0.13,
      ampX: 4,
      ampY: 4,
      rotAmp: 5,
      scaleAmp: 0.07,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-beirut-streets.jpg",
      alt: "Beirut street performance — deep archive print",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-flash-qbert",
      pos: { left: 44.8, top: 3 },
      w: 3.5,
      rot: 2,
      period: 58,
      phase: 0.27,
      ampX: 4,
      ampY: 4,
      rotAmp: -4,
      scaleAmp: 0.06,
      presence: { period: 63, phase: 0.3, min: 0.3 },
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-qbert.jpg",
      alt: "Skillz with DJ Q-Bert — deep archive print",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-flash-ufo",
      pos: { left: 38.3, top: 87.1 },
      w: 3,
      rot: -1,
      period: 66,
      phase: 0.41,
      ampX: 4,
      ampY: 4,
      rotAmp: 3,
      scaleAmp: 0.07,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-ufo-badge.png",
      alt: "UFO Radio badge — deep archive",
      variant: "pass",
      tier: "background",
    },
    {
      id: "d-flash-jazzy",
      pos: { left: 31.4, top: 94 },
      w: 3.5,
      rot: 3,
      period: 44,
      phase: 0.59,
      ampX: 4,
      ampY: 4,
      rotAmp: -3,
      scaleAmp: 0.06,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-jazzy-jeff.jpg",
      alt: "Skillz with DJ Jazzy Jeff — deep archive print",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-flash-breaking",
      pos: { left: 51.4, top: 16.3 },
      w: 3,
      rot: -2,
      period: 53,
      phase: 0.71,
      ampX: 4,
      ampY: 4,
      rotAmp: 4,
      scaleAmp: 0.07,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-breaking.jpg",
      alt: "Red Bull breaking battle — deep archive print",
      variant: "flyer",
      tier: "background",
    },
    {
      id: "d-flash-cutkiller",
      pos: { left: 73.3, top: 3 },
      w: 3,
      rot: 1,
      period: 61,
      phase: 0.18,
      ampX: 4,
      ampY: 4,
      rotAmp: -5,
      scaleAmp: 0.06,
      presence: { period: 70, phase: 0.5, min: 0.35 },
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-cut-killer.jpg",
      alt: "Skillz with DJ Cut Killer — deep archive print",
      variant: "flyer",
      tier: "background",
    },
    {
      id: "d-flash-stussy",
      pos: { left: 62.9, top: 87.3 },
      w: 3.5,
      rot: -2,
      period: 49,
      phase: 0.85,
      ampX: 4,
      ampY: 4,
      rotAmp: 2,
      scaleAmp: 0.06,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-stussy.jpg",
      alt: "Stussy launch party — deep archive print",
      variant: "instant",
      tier: "background",
    },
    // ── DEEP ARCHIVE LAYER (batch 2) — unique archival material, quieter
    // and slower than the existing deep tier. Labels follow the verification
    // policy: named only where identity is verified, otherwise bare prints.
    {
      id: "d-archive-apollo",
      pos: { left: 38.7, top: 3 },
      w: 3,
      rot: -2,
      period: 62,
      phase: 0.12,
      ampX: 4,
      ampY: 4,
      rotAmp: 3,
      scaleAmp: 0.06,
      mobile: true,
      layer: "deep",
      label: "WITH DJ APOLLO",
      context: "Invisibl Skratch Piklz",
      media: "/assets/fragments/fragments-deep-apollo.jpg",
      alt: "Skillz with DJ Apollo — archive print",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-archive-zenfu",
      pos: { left: 3, top: 51.5 },
      w: 3,
      rot: 2,
      period: 55,
      phase: 0.63,
      ampX: 4,
      ampY: 4,
      rotAmp: -3,
      scaleAmp: 0.06,
      mobile: true,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-deep-zenfu.jpg",
      alt: "Skillz at Zen Fu with the monks — archive photograph",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-archive-karmageddon",
      pos: { left: 87.1, top: 94 },
      w: 3,
      rot: -3,
      period: 59,
      phase: 0.41,
      ampX: 4,
      ampY: 4,
      rotAmp: 4,
      scaleAmp: 0.07,
      mobile: true,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-deep-karmageddon.jpg",
      alt: "Karmageddon — DJ Lethal Skillz sophomore album cover",
      variant: "flyer",
      tier: "background",
    },
    {
      id: "d-archive-radio-beirut",
      pos: { left: 3, top: 15.2 },
      w: 3.5,
      rot: 2,
      period: 67,
      phase: 0.88,
      ampX: 4,
      ampY: 4,
      rotAmp: -3,
      scaleAmp: 0.06,
      mobile: true,
      layer: "deep",
      label: "RADIO BEIRUT",
      media: "/assets/fragments/fragments-deep-radio-beirut.jpg",
      alt: "Skillz live on Radio Beirut — archive photograph",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-archive-dmc",
      pos: { left: 68.4, top: 84.5 },
      w: 3,
      rot: -1,
      period: 71,
      phase: 0.35,
      ampX: 4,
      ampY: 4,
      rotAmp: 2,
      scaleAmp: 0.07,
      layer: "deep",
      label: "DMC WORLD CHAMPIONSHIP",
      context: "GCC Battles · Dubai",
      media: "/assets/fragments/fragments-deep-dmc.jpg",
      alt: "DMC World Championship GCC battles, Dubai — archive photograph",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-archive-dragon-temple",
      pos: { left: 11.8, top: 18.6 },
      w: 3,
      rot: 1,
      period: 47,
      phase: 0.77,
      ampX: 4,
      ampY: 4,
      rotAmp: -4,
      scaleAmp: 0.06,
      layer: "deep",
      label: "DRAGON TEMPLE",
      media: "/assets/fragments/fragments-deep-dragon-temple.jpg",
      alt: "Dragon Temple music video shoot — archive photograph",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-archive-straight-apex",
      pos: { left: 14.4, top: 80.7 },
      w: 2.5,
      rot: -2,
      period: 63,
      phase: 0.22,
      ampX: 4,
      ampY: 4,
      rotAmp: 3,
      scaleAmp: 0.07,
      layer: "deep",
      label: "STRAIGHT OUTTA APEX",
      context: "Zouk · Kuala Lumpur",
      media: "/assets/fragments/fragments-deep-straight-apex.jpg",
      alt: "Straight Outta Apex, Zouk Kuala Lumpur — archive photograph",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-archive-zion",
      pos: { left: 74.6, top: 87.5 },
      w: 3,
      rot: -1,
      period: 51,
      phase: 0.94,
      ampX: 4,
      ampY: 4,
      rotAmp: 2,
      scaleAmp: 0.06,
      layer: "deep",
      label: "ZION CLUB · ROOM 808",
      media: "/assets/fragments/fragments-deep-zion.jpg",
      alt: "Zion Club Room 808, Kuala Lumpur — archive photograph",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-archive-afora",
      pos: { left: 3.07, top: 86.8 },
      w: 3,
      rot: 2,
      period: 73,
      phase: 0.58,
      ampX: 4,
      ampY: 4,
      rotAmp: -3,
      scaleAmp: 0.06,
      layer: "deep",
      label: "AFORA RADIO",
      media: "/assets/fragments/fragments-deep-afora.jpg",
      alt: "Skillz live on AFORA Radio — archive photograph",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-archive-stussy-kl",
      pos: { left: 79.6, top: 21.8 },
      w: 3,
      rot: -2,
      period: 45,
      phase: 0.06,
      ampX: 4,
      ampY: 4,
      rotAmp: 4,
      scaleAmp: 0.07,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-deep-stussy-kl.jpg",
      alt: "Stussy KL event — archive photograph",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-archive-workshop",
      pos: { left: 97, top: 54.8 },
      w: 3,
      rot: 1,
      period: 69,
      phase: 0.49,
      ampX: 4,
      ampY: 4,
      rotAmp: -2,
      scaleAmp: 0.06,
      tablet: false,
      layer: "deep",
      label: "HOME GROWN TURNTABLISM",
      media: "/assets/fragments/fragments-deep-workshop.jpg",
      alt: "School of Homegrown Turntablism workshop, Malaysia — archive photograph",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-archive-fb-group",
      pos: { left: 88.9, top: 9.27 },
      w: 3,
      rot: -1,
      period: 57,
      phase: 0.31,
      ampX: 4,
      ampY: 4,
      rotAmp: 3,
      scaleAmp: 0.06,
      tablet: false,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-deep-fb-10face.jpg",
      alt: "From the Skillz archive — event photograph",
      variant: "instant",
      tier: "background",
    },
    {
      id: "d-archive-fb-live",
      pos: { left: 3, top: 71.5 },
      w: 2.5,
      rot: 2,
      period: 65,
      phase: 0.82,
      ampX: 4,
      ampY: 4,
      rotAmp: -4,
      scaleAmp: 0.07,
      tablet: false,
      layer: "deep",
      label: false,
      media: "/assets/fragments/fragments-deep-fb-4face.jpg",
      alt: "From the Skillz archive — performance photograph",
      variant: "instant",
      tier: "background",
    },
    // ── FINAL CURATION — gap fillers from the 89-image audit ────────────
    // Crew + place labels from filenames only; faces unverified → unlabeled.
    {
      id: "cur-poland",
      pos: { left: 3, top: 78.6 },
      w: 4,
      rot: 1,
      period: 49,
      phase: 0.12,
      ampX: 4,
      ampY: 5,
      rotAmp: 2,
      scaleAmp: 0.06,
      layer: "secondary",
      label: "961 UNDERGROUND FAMILY",
      mobile: true,
      media: "/assets/fragments/fragments-cur-poland.jpg",
      alt: "With the 961 Underground Family in Poland — archive photograph",
      variant: "instant",
      tier: "supporting",
    },
    {
      id: "cur-961",
      pos: { left: 67.1, top: 94 },
      w: 3.5,
      rot: -2,
      period: 58,
      phase: 0.73,
      ampX: 4,
      ampY: 4,
      rotAmp: -3,
      scaleAmp: 0.07,
      layer: "deep",
      label: false,
      mobile: true,
      media: "/assets/fragments/fragments-cur-961.jpg",
      alt: "961 Underground graffiti — archive photograph",
      variant: "instant",
      tier: "background",
    },
    {
      id: "cur-record-shop",
      pos: { left: 17.4, top: 30.1 },
      w: 3.5,
      rot: 2,
      period: 66,
      phase: 0.41,
      ampX: 4,
      ampY: 4,
      rotAmp: 3,
      scaleAmp: 0.06,
      layer: "secondary",
      label: "RECORD SHOP · KL",
      media: "/assets/fragments/fragments-cur-record-shop.jpg",
      alt: "Record shop in Kuala Lumpur — archive photograph",
      variant: "instant",
      tier: "supporting",
    },
    {
      id: "cur-vibe-lebanon",
      pos: { left: 97, top: 13.6 },
      w: 3.5,
      rot: -1,
      period: 53,
      phase: 0.28,
      ampX: 4,
      ampY: 4,
      rotAmp: -2,
      scaleAmp: 0.06,
      layer: "secondary",
      label: "VIBE LEBANON",
      context: "Old Online Radio Station",
      media: "/assets/fragments/fragments-cur-vibe-lebanon.jpg",
      alt: "Vibe Lebanon radio workshop — archive photograph",
      variant: "instant",
      tier: "supporting",
    },
    {
      id: "cur-video-shoot",
      pos: { left: 78.2, top: 94 },
      w: 4,
      rot: 3,
      period: 61,
      phase: 0.87,
      ampX: 4,
      ampY: 5,
      rotAmp: 4,
      scaleAmp: 0.07,
      tablet: false,
      mobile: true,
      layer: "secondary",
      label: "VIDEO SHOOT · KL 2 BEIRUT",
      media: "/assets/fragments/fragments-cur-video-shoot.jpg",
      alt: "Music video shoot, Kuala Lumpur to Beirut — archive photograph",
      variant: "instant",
      tier: "supporting",
    },
    {
      id: "cur-redbull-crowd",
      pos: { left: 96.3, top: 60.4 },
      w: 4.5,
      rot: -1,
      period: 47,
      phase: 0.64,
      ampX: 5,
      ampY: 4,
      rotAmp: -3,
      scaleAmp: 0.08,
      layer: "secondary",
      label: false,
      mobile: true,
      media: "/assets/fragments/fragments-cur-redbull-crowd.jpg",
      alt: "Red Bull event crowd — archive photograph",
      variant: "instant",
      tier: "supporting",
    },
    {
      id: "cur-performance",
      pos: { left: 89.8, top: 81.6 },
      w: 4,
      rot: 2,
      period: 71,
      phase: 0.09,
      ampX: 5,
      ampY: 4,
      rotAmp: 2,
      scaleAmp: 0.06,
      layer: "secondary",
      label: false,
      media: "/assets/fragments/fragments-cur-performance.jpg",
      alt: "From the Skillz archive — DJ performance photograph",
      variant: "instant",
      tier: "supporting",
    },
    {
      id: "cur-interview",
      pos: { left: 15, top: 64.2 },
      w: 4,
      rot: -2,
      period: 59,
      phase: 0.35,
      ampX: 4,
      ampY: 4,
      rotAmp: -4,
      scaleAmp: 0.07,
      layer: "secondary",
      label: false,
      media: "/assets/fragments/fragments-cur-interview.jpg",
      alt: "From the Skillz archive — interview photograph",
      variant: "instant",
      tier: "supporting",
    },
    {
      id: "cur-secondary-a",
      pos: { left: 90.3, top: 56.2 },
      w: 3,
      rot: 1,
      period: 63,
      phase: 0.55,
      ampX: 4,
      ampY: 4,
      rotAmp: 3,
      scaleAmp: 0.06,
      tablet: false,
      layer: "secondary",
      label: false,
      media: "/assets/fragments/fragments-cur-secondary-a.jpg",
      alt: "From the Skillz archive — event photograph",
      variant: "instant",
      tier: "supporting",
    },
    {
      id: "cur-secondary-b",
      pos: { left: 87.4, top: 39.6 },
      w: 3.5,
      rot: -3,
      period: 52,
      phase: 0.92,
      ampX: 4,
      ampY: 4,
      rotAmp: -2,
      scaleAmp: 0.06,
      layer: "secondary",
      label: false,
      media: "/assets/fragments/fragments-cur-secondary-b.jpg",
      alt: "From the Skillz archive — event photograph",
      variant: "instant",
      tier: "supporting",
    },
    {
      id: "cur-flyer-ace",
      pos: { left: 3, top: 34.8 },
      w: 3.5,
      rot: 2,
      period: 44,
      phase: 0.18,
      ampX: 4,
      ampY: 5,
      rotAmp: 2,
      scaleAmp: 0.07,
      label: false,
      mobile: true,
      variant: "flyer",
      tier: "supporting",
      media: "/assets/fragments/fragments-cur-flyer-ace.jpg",
      alt: "ACE at Zouk, Kuala Lumpur — event flyer",
    },
    {
      id: "cur-flyer-3styles",
      pos: { left: 64.7, top: 15.5 },
      w: 3.5,
      rot: -2,
      period: 68,
      phase: 0.47,
      ampX: 4,
      ampY: 4,
      rotAmp: -3,
      scaleAmp: 0.06,
      label: false,
      variant: "flyer",
      tier: "supporting",
      media: "/assets/fragments/fragments-cur-flyer-3styles.jpg",
      alt: "Red Bull 3Style Lebanon judging — event flyer",
    },
    {
      id: "cur-flyer-karmageddon",
      pos: { left: 5.02, top: 24.4 },
      w: 5,
      rot: 1,
      period: 57,
      phase: 0.71,
      ampX: 4,
      ampY: 4,
      rotAmp: 2,
      scaleAmp: 0.06,
      label: false,
      variant: "flyer",
      tier: "supporting",
      media: "/assets/fragments/fragments-cur-flyer-karmageddon.jpg",
      alt: "Karmageddon — wide-format event banner",
    },
    {
      id: "cur-flyer-klpac",
      pos: { left: 20.9, top: 77.9 },
      w: 3,
      rot: -1,
      period: 46,
      phase: 0.03,
      ampX: 4,
      ampY: 4,
      rotAmp: -2,
      scaleAmp: 0.07,
      tablet: false,
      label: false,
      variant: "flyer",
      tier: "supporting",
      media: "/assets/fragments/fragments-cur-flyer-klpac.jpg",
      alt: "KLPAC 2013 — event flyer",
    },
    {
      id: "cur-flyer-workshop",
      pos: { left: 76.3, top: 67.3 },
      w: 3,
      rot: 2,
      period: 72,
      phase: 0.6,
      ampX: 4,
      ampY: 4,
      rotAmp: 3,
      scaleAmp: 0.06,
      label: false,
      variant: "flyer",
      tier: "supporting",
      media: "/assets/fragments/fragments-cur-flyer-workshop.jpg",
      alt: "Turntablism education workshop — event flyer",
    },
  ] as FieldFragment[],

  /** PEOPLE scene — the field of relationships, strongest first. */
  peopleTrack: [
    "qbert",
    "tony-touch-apollo-vinroc",
    "keith-shocklee",
    "sueside",
    "rob-swift",
    "nu-mark",
    "naughty-j",
    "mims",
    "primecuts",
    "big-ali-mice",
    "japan-champions",
    "coma-sarasa",
  ],

  /** PLACES scene — geography as an editorial sequence (images cross the markers). */
  places: [
    { city: "BEIRUT", context: "Street Performance", itemId: "beirut-streets" },
    { city: "DUBAI", context: "DMC World Championship", itemId: "akakabe-dmc" },
    { city: "JAPAN", context: "The DMC Champions", itemId: "sarasa" },
    { city: "LONDON", context: "One Nation Under A Groove", itemId: "one-nation" },
    { city: "FRANCE", context: "Paris · The French Scene", itemId: "cut-killer" },
    { city: "USA", context: "Philadelphia · New York", itemId: "jazzy-jeff" },
    { city: "PHNOM PENH", context: "Cambodia · Southeast Asia", itemId: "cambodia" },
  ],

  /** MOMENTS & EVIDENCE scene — the archive resolving toward its documents. */
  moments: [
    "one-nation",
    "3style",
    "breaking",
    "studio-2012",
    "stussy",
    "ufo-badge",
  ],

  /** Display order = array order within each band. */
  items: [
    // ── PEOPLE ────────────────────────────────────────────────────────────
    {
      id: "qbert",
      media: "/assets/fragments/fragments-qbert.jpg",
      band: "people",
      name: "DJ Q-BERT",
      context: "DMC World Championship · Dubai · Judge",
      alt: "Skillz with DJ Q-Bert at the DMC World Championship, Dubai 2007",
      span: "md:col-span-2",
      aspect: "aspect-[4/3]",
    },
    {
      id: "akakabe-dmc",
      media: "/assets/fragments/fragments-akakabe-dmc.jpg",
      band: "people",
      name: "DJ AKAKABE",
      context: "DMC World Championship · Dubai",
      alt: "Skillz with DJ Akakabe at the DMC World Championship, Dubai",
      aspect: "aspect-[4/3]",
    },
    {
      id: "japan-champions",
      media: "/assets/fragments/fragments-japan-champions.jpg",
      band: "people",
      name: "JAPAN DMC CHAMPIONS",
      context: "Akakabe · Coma",
      alt: "Japan's DMC Champions Akakabe and Coma with Skillz",
      aspect: "aspect-[4/3]",
    },
    {
      id: "coma-sarasa",
      media: "/assets/fragments/fragments-coma-sarasa.jpg",
      band: "people",
      name: "COMA & SARASA",
      context: "Japan",
      alt: "Skillz with DJ Coma and DJ Sarasa, Japan",
      aspect: "aspect-[4/3]",
    },
    {
      id: "sarasa",
      media: "/assets/fragments/fragments-sarasa.jpg",
      band: "people",
      name: "DJ SARASA",
      context: "Japan",
      alt: "Skillz with DJ Sarasa, Japan",
      aspect: "aspect-[4/3]",
    },
    {
      id: "tony-touch-apollo-vinroc",
      media: "/assets/fragments/fragments-tony-touch-apollo-vinroc.jpg",
      band: "people",
      name: "TONY TOUCH · APOLLO · VINROC",
      context: "Rocksteady Crew · Invisibl Skratch Piklz · 5th Platoon",
      alt: "Skillz with DJ Tony Touch, DJ Apollo and Vinroc",
      span: "md:col-span-2",
      aspect: "aspect-square",
    },
    {
      id: "tony-touch",
      media: "/assets/fragments/fragments-tony-touch.jpg",
      band: "people",
      name: "DJ TONY TOUCH",
      alt: "Skillz with DJ Tony Touch",
      aspect: "aspect-square",
    },
    {
      id: "jazzy-jeff",
      media: "/assets/fragments/fragments-jazzy-jeff.jpg",
      band: "people",
      name: "DJ JAZZY JEFF",
      alt: "Skillz with DJ Jazzy Jeff",
      aspect: "aspect-[5/6]",
    },
    {
      id: "rob-swift",
      media: "/assets/fragments/fragments-rob-swift.jpg",
      band: "people",
      name: "ROB SWIFT",
      alt: "Skillz with Rob Swift",
      aspect: "aspect-[3/4]",
    },
    {
      id: "keith-shocklee",
      media: "/assets/fragments/fragments-keith-shocklee.jpg",
      band: "people",
      name: "KEITH SHOCKLEE",
      alt: "Skillz with Keith Shocklee",
      aspect: "aspect-square",
    },
    {
      id: "sueside",
      media: "/assets/fragments/fragments-sueside.jpg",
      band: "people",
      name: "GRAND MASTER SUESIDE",
      context: "Wu-Tang DJ",
      alt: "Skillz with Grand Master Sueside, Wu-Tang DJ",
      aspect: "aspect-[4/3]",
    },
    {
      id: "mims",
      media: "/assets/fragments/fragments-mims.jpg",
      band: "people",
      name: "MIMS",
      context: "This Is Why I'm Hot",
      alt: "Skillz with MIMS",
      aspect: "aspect-[4/3]",
    },
    {
      id: "primecuts",
      media: "/assets/fragments/fragments-primecuts.jpg",
      band: "people",
      name: "DJ PRIMECUTS",
      context: "Scratch Perverts",
      alt: "Skillz with DJ Primecuts of the Scratch Perverts",
      aspect: "aspect-[3/4]",
    },
    {
      id: "cut-killer",
      media: "/assets/fragments/fragments-cut-killer.jpg",
      band: "people",
      name: "DJ CUT KILLER",
      context: "France",
      alt: "Skillz with DJ Cut Killer, France",
      span: "md:col-span-2",
      aspect: "aspect-[3/2]",
    },
    {
      id: "naughty-j",
      media: "/assets/fragments/fragments-naughty-j.jpg",
      band: "people",
      name: "DJ NAUGHTY J",
      context: "NTM",
      alt: "Skillz with DJ Naughty J of NTM",
      aspect: "aspect-square",
    },
    {
      id: "big-ali-mice",
      media: "/assets/fragments/fragments-big-ali-mice.jpg",
      band: "people",
      name: "BIG ALI & DJ M.ICE",
      alt: "Skillz with Big Ali and DJ M.ICE",
      aspect: "aspect-[4/3]",
    },
    {
      id: "nu-mark",
      media: "/assets/fragments/fragments-nu-mark.jpg",
      band: "people",
      name: "DJ NU-MARK",
      alt: "Skillz with DJ Nu-Mark",
      aspect: "aspect-square",
    },

    // ── PLACES ────────────────────────────────────────────────────────────
    {
      id: "beirut-streets",
      media: "/assets/fragments/fragments-beirut-streets.jpg",
      band: "places",
      name: "BEIRUT",
      context: "Street Performance",
      alt: "Skillz scratching on the streets of Beirut",
      span: "md:col-span-2",
      aspect: "aspect-[16/9]",
    },
    {
      id: "cambodia",
      media: "/assets/fragments/fragments-cambodia.jpg",
      band: "places",
      name: "CAMBODIA",
      context: "Performance · Southeast Asia",
      alt: "Skillz performing in Cambodia, Southeast Asia",
      aspect: "aspect-[3/4]",
    },

    // ── MOMENTS ───────────────────────────────────────────────────────────
    {
      id: "one-nation",
      media: "/assets/fragments/fragments-one-nation.jpg",
      band: "moments",
      name: "ONE NATION UNDER A GROOVE",
      context: "M1 · Dead Prez · Pharoahe Monch",
      alt: "One Nation Under A Groove with M1, Dead Prez and Pharoahe Monch",
      span: "md:col-span-2",
      aspect: "aspect-[4/5]",
    },
    {
      id: "breaking",
      media: "/assets/fragments/fragments-breaking.jpg",
      band: "moments",
      name: "RED BULL BREAKING",
      alt: "A Red Bull breaking battle, Lebanon",
      aspect: "aspect-[2/3]",
    },
    {
      id: "3style",
      media: "/assets/fragments/fragments-3style.jpg",
      band: "moments",
      name: "RED BULL 3STYLE",
      context: "Judge · Lebanon",
      alt: "Skillz judging at the Red Bull 3Style world DJ championship, Lebanon",
      aspect: "aspect-[16/10]",
    },
    {
      id: "studio-2012",
      media: "/assets/fragments/fragments-studio-2012.jpg",
      band: "moments",
      name: "STUDIO SESSION",      alt: "Skillz in a studio session, May 4 2012",
      span: "md:col-span-2",
      aspect: "aspect-[4/3]",
    },
    {
      id: "stussy",
      media: "/assets/fragments/fragments-stussy.jpg",
      band: "moments",
      name: "STUSSY LAUNCH PARTY",
      alt: "A Stussy launch party with Skillz",
      span: "md:col-span-2",
      aspect: "aspect-[3/2]",
    },

    // ── EVIDENCE ──────────────────────────────────────────────────────────
    {
      id: "ufo-badge",
      media: "/assets/fragments/fragments-ufo-badge.png",
      band: "evidence",
      name: "UFO RADIO",
      context: "DJ Lethal Skillz · Badge",
      alt: "UFO Radio badge of DJ Lethal Skillz",
      aspect: "aspect-[4/3]",
    },
  ] satisfies FragmentsItem[],
};
